### ISSUE TITLE
Homepage graphic are showing images with NO votes as well as those WITH votes

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#35]

**Comment by frankradocaj** [comment]
The logic used to determine which sightings show up on the homepage at the top (I take it that is what you mean by "Homepage graphic") is:
- Order sightings by date, latest at top;
- Order by number of votes, most at top;
- Take top 10.

So, if there aren't at least 10 sightings that _have votes_, then it will load sighting images _without_ votes. This ensures that at least _something_ gets displayed on the homepage. This is by design.
